using System.Collections.Generic;

namespace Logistics.DbMerger
{
    public static class MigrationConfig
    {
        // Define the explicit order of tables for migration (Tiers 1-8)
        public static readonly List<string> TableOrder = new List<string>
        {
            // 4.1 Tier 1 - Reference/Lookup Tables
            "Tenants",
            "Languages",
            "Editions",
            "Features",
            "Status",
            "ReasonType",
            "Reason",
            "BudgetType",
            "DiscussionType",
            "OutcomeType",
            "ThreadType",
            "SubThreadType",
            "ConsultationType",
            "TaskType",
            "WorkType",
            "VolumeType",
            "UnitType",
            "PalletType",
            "TemplateType",
            "RateType",
            "LeaveType",
            "PublicHolidayGroup",
            "PublicHolidayGroupDay",
            "RDOGroup",
            "RDOGroupDetail",

            // 4.2 Tier 2 - Core Entity Tables
            "Grade",
            "Position",
            "EmploymentType",
            "EmploymentAgency",
            "ManagerGroup",
            "Shift",
            "RosterPattern",
            "RosterPatternDetail",
            "RosterPatternDetailItem",
            "EBA",
            "EBAGradeRate",
            "Function",
            "Area",
            "AreaClockNum",
            "Chamber",
            "ChamberFloorCapacity",
            "Qualification",
            "QualificationMatrix",
            "CoverageGroup",
            "FilterGroup",
            "DayDefinition",
            "CommentTemplate",
            "DoomDashboardTemplate",

            // 4.3 Tier 3 - Primary Operational Tables
            "Contact",
            "ContactRDOGroup",
            "Users",
            "UserAccounts",
            "UserRoles",
            "UserClaims",
            "UserLogins",
            "UserLoginAttempts",
            "UserNotifications",
            "UserOrganizationUnits",
            "OrganizationUnits",
            "ManagerGroupUser",
            "ContactFilterGroups",
            "ContactQualification",
            "ContactQualificationAreaTask",
            "ContactQualificationSuspension",
            "ContactEBA",
            "ContactPerformance",
            "ContactLMPerformance",
            "ContactNotification",

            // 4.4 Tier 4 - Transactional Tables
            "Task",
            "LeaveRequest",
            "LeaveBalance",
            "LeaveBlackOut",
            "Attachment",
            "ContactComments",
            "ContactDiscussion",
            "TemplateSchedule",
            "TemplateScheduleDetail",
            "ContactTemplateSchedule",
            "ContactTemplateScheduleOverride",
            "Budget",
            "FloorCapacity",
            "CommercialShift",
            "CommercialVolume",
            "LoadManagementCalc",

            // 4.5 Tier 5 - High-Volume Operational Tables
            "TimebandHeader",
            "Timeband",
            "TimebandDetail",
            "TimebandDetailBreakdown",
            "TimebandShiftBid",
            "PlannedTimeband",
            "PlannedTimebandDetail",
            "ForecastTimeband",
            "ForecastTimebandDetail",
            "LastRosteredTimeband",
            "ClockEvent",
            "IndirectClockEvent", // ADC Name
            "IndirectClockEvents", // MDC Name (Explicitly mapped, but listed for completeness)
            "ClockingTransactionSyncTempDatas",
            "ClockIntegrationSyncJobHistories",
            "VolumeBlockData",
            "VolumeDetail",
            "VolumeDetailAudit",
            "VolumeDetailMaster",
            "BulkVolumeDetail",

            // 4.6 Tier 6 - Secondary/Support Tables
            "ShiftBid",
            "ShiftBidDetail",
            "ShiftDailyWeeklyLimit",
            "ShiftMoveReason",
            "ShiftScheduleTemplate",
            "ShiftScheduleTemplateBreak",
            "PlannedShiftBidOffers",
            "ContactShiftBid",
            "ReturnToWorkHeader",
            "ReturntoWorkPlan",
            "ReturnToWorkActivity",
            "ReturnToWorkConsultation",
            "ReturntoWorkGoal",
            "ReturnToWorkHeaderGoal",
            "ReturntoWorkPlanRestriction",
            "ReturnToWorkPlanDistribution",
            "TrainingPlan",
            "TrainingPlanInstance",
            "TrainingPlanQualification",
            "TrainingPlanInstanceQualification",
            "TrainingReason",
            "TrainingTask",
            "ContactTrainingPlanInstance",

            // 4.7 Tier 7 - Rules & Audit Tables
            "ruletype",
            "ruleset",
            "Rule",
            "rulesetrule",
            "rulecalculation",
            "rulecalculationdependant",
            "ruleprocessingqueue",
            "ProcessedRule",
            "AuditLogs",
            "EntityAuditLog",
            "BackgroundJobs",

            // 4.8 Tier 8 - Notifications & Settings
            "Setting",
            "Settings",
            "IntegrationSettings",
            "IntegrationException",
            "ExternalIntegrationQueue",
            "Notifications",
            "NotificationSubscriptions",
            "NotificationFilterTemplate",
            "HomeNotification",
            "HomeNotificationLog",
            "TenantNotifications",
            "ReportNotifications",
            "SftpReportHistory",
            "TAImportRecords",
            "GlobalFilter",
            "Permissions",
            "Roles",
            "LastUpdateBiarri",
            "DespatchTMS",
            "AbsenteeismRate",
            "TeamMemberPerformance",
            "WrongFunctionLog",
            "WrongFunctionTaskControl"
        };
    }
}
